var locations = [
	{"internal_name":"{{NoName}}", "display_name":"{{NoName}}", "x":4364, "y":3560},
	{"internal_name":"{Location_Cokiri:ShopYadoya}", "display_name":"{Location_Cokiri:ShopYadoya}", "x":3203, "y":1411},
	{"internal_name":"{Location_Cokiri:ShopYorozu}", "display_name":"{Location_Cokiri:ShopYorozu}", "x":3217, "y":1409},
	{"internal_name":"{Location_Gerudo:ShopBougu}", "display_name":"{Location_Gerudo:ShopBougu}", "x":1096, "y":3953},
	{"internal_name":"{Location_Gerudo:ShopJewel}", "display_name":"{Location_Gerudo:ShopJewel}", "x":1081, "y":3938},
	{"internal_name":"{Location_Gerudo:ShopYadoya}", "display_name":"{Location_Gerudo:ShopYadoya}", "x":1074, "y":3945},
	{"internal_name":"{Location_Gerudo:ShopYorozu}", "display_name":"{Location_Gerudo:ShopYorozu}", "x":1071, "y":3956},
	{"internal_name":"{Location_Gerudo:ShopYorozu}", "display_name":"{Location_Gerudo:ShopYorozu}", "x":1075, "y":3951},
	{"internal_name":"{Location_Gerudo:ShopYorozu}", "display_name":"{Location_Gerudo:ShopYorozu}", "x":1088, "y":3939},
	{"internal_name":"{Location_Gerudo:ShopYorozu}", "display_name":"{Location_Gerudo:ShopYorozu}", "x":1089, "y":3968},
	{"internal_name":"{Location_Gerudo:ShopYorozu}", "display_name":"{Location_Gerudo:ShopYorozu}", "x":1090, "y":3962},
	{"internal_name":"{Location_Goron:ShopBougu}", "display_name":"{Location_Goron:ShopBougu}", "x":3821, "y":1295},
	{"internal_name":"{Location_Goron:ShopYadoya}", "display_name":"{Location_Goron:ShopYadoya}", "x":3841, "y":1287},
	{"internal_name":"{Location_Goron:ShopYorozu}", "display_name":"{Location_Goron:ShopYorozu}", "x":3833, "y":1265},
	{"internal_name":"{Location_Goron:ShopYorozu}", "display_name":"{Location_Goron:ShopYorozu}", "x":3841, "y":1268},
	{"internal_name":"{Location_Hateno:ShopBougu}", "display_name":"{Location_Hateno:ShopBougu}", "x":4678, "y":3563},
	{"internal_name":"{Location_Hateno:ShopColor}", "display_name":"{Location_Hateno:ShopColor}", "x":4701, "y":3576},
	{"internal_name":"{Location_Hateno:ShopYadoya}", "display_name":"{Location_Hateno:ShopYadoya}", "x":4736, "y":3555},
	{"internal_name":"{Location_Hateno:ShopYorozu}", "display_name":"{Location_Hateno:ShopYorozu}", "x":4680, "y":3585},
	{"internal_name":"{Location_Kakariko:ShopBougu}", "display_name":"{Location_Kakariko:ShopBougu}", "x":3927, "y":2990},
	{"internal_name":"{Location_Kakariko:ShopYadoya}", "display_name":"{Location_Kakariko:ShopYadoya}", "x":3917, "y":3010},
	{"internal_name":"{Location_Kakariko:ShopYorozu}", "display_name":"{Location_Kakariko:ShopYorozu}", "x":3897, "y":3014},
	{"internal_name":"{Location_Kakariko:ShopYorozu}", "display_name":"{Location_Kakariko:ShopYorozu}", "x":3912, "y":3020},
	{"internal_name":"{Location_Oasis:ShopYadoya}", "display_name":"{Location_Oasis:ShopYadoya}", "x":1366, "y":3805},
	{"internal_name":"{Location_Oasis:ShopYorozu}", "display_name":"{Location_Oasis:ShopYorozu}", "x":1361, "y":3782},
	{"internal_name":"{Location_Oasis:ShopYorozu}", "display_name":"{Location_Oasis:ShopYorozu}", "x":1369, "y":3801},
	{"internal_name":"{Location_Oasis:ShopYorozu}", "display_name":"{Location_Oasis:ShopYorozu}", "x":1379, "y":3763},
	{"internal_name":"{Location_Rito:ShopBougu}", "display_name":"{Location_Rito:ShopBougu}", "x":1184, "y":1606},
	{"internal_name":"{Location_Rito:ShopYadoya}", "display_name":"{Location_Rito:ShopYadoya}", "x":1193, "y":1573},
	{"internal_name":"{Location_Rito:ShopYorozu}", "display_name":"{Location_Rito:ShopYorozu}", "x":1177, "y":1589},
	{"internal_name":"{Location_Taura:ShopYadoya}", "display_name":"{Location_Taura:ShopYadoya}", "x":4472, "y":4218},
	{"internal_name":"{Location_Taura:ShopYorozu}", "display_name":"{Location_Taura:ShopYorozu}", "x":4479, "y":4246},
	{"internal_name":"{Location_UMiiVillageShopBougu:ShopBougu}", "display_name":"{Location_UMiiVillageShopBougu:ShopBougu}", "x":4979, "y":1681},
	{"internal_name":"{Location_UMiiVillageShopJewel:ShopJewel}", "display_name":"{Location_UMiiVillageShopJewel:ShopJewel}", "x":4975, "y":1686},
	{"internal_name":"{Location_UMiiVillageShopYadoya:ShopYadoya}", "display_name":"{Location_UMiiVillageShopYadoya:ShopYadoya}", "x":4999, "y":1702},
	{"internal_name":"{Location_UMiiVillageShopYorozu:ShopYorozu}", "display_name":"{Location_UMiiVillageShopYorozu:ShopYorozu}", "x":4975, "y":1703},
	{"internal_name":"{Location_WhiteZora:ShopYadoya}", "display_name":"{Location_WhiteZora:ShopYadoya}", "x":4648, "y":2245},
	{"internal_name":"{Location_WhiteZora:ShopYorozu}", "display_name":"{Location_WhiteZora:ShopYorozu}", "x":4661, "y":2254},
	{"internal_name":"AdeyaVillage", "display_name":"Deya Village Ruins", "x":3176, "y":3476},
	{"internal_name":"AkkareBigBridge", "display_name":"Akkala Span", "x":4504, "y":1878},
	{"internal_name":"AkkareGarrison", "display_name":"Akkala Parade Ground Ruins", "x":4654, "y":1899},
	{"internal_name":"AkkareZhai", "display_name":"Akkala Citadel Ruins", "x":4667, "y":1773},
	{"internal_name":"AkkareZhaiBridge", "display_name":"Akkala Bridge Ruins", "x":4575, "y":1805},
	{"internal_name":"AncientLabo", "display_name":"Akkala Ancient Tech Lab", "x":5257, "y":917},
	{"internal_name":"Assassin", "display_name":"Yiga Clan Hideout", "x":1203, "y":3190},
	{"internal_name":"BigBrotherBridge", "display_name":"Big Twin Bridge", "x":3835, "y":3516},
	{"internal_name":"BigTree", "display_name":"Ancient Tree Stump", "x":2446, "y":2722},
	{"internal_name":"BraveFountain", "display_name":"Spring of Courage", "x":3438, "y":3685},
	{"internal_name":"BrosRock", "display_name":"Warbler's Nest", "x":1006, "y":1624},
	{"internal_name":"CastleTownMark", "display_name":"Hyrule Castle Town Ruins", "x":2872, "y":2346},
	{"internal_name":"CelebrationPark", "display_name":"Sacred Ground Ruins", "x":2873, "y":2461},
	{"internal_name":"CentralExchange", "display_name":"Exchange Ruins", "x":2628, "y":2934},
	{"internal_name":"ChirakaVillage", "display_name":"Goponga Village Ruins", "x":3808, "y":2631},
	{"internal_name":"Cohorint", "display_name":"Eventide Island", "x":5302, "y":4323},
	{"internal_name":"Cokiri", "display_name":"Korok Forest", "x":3213, "y":1431},
	{"internal_name":"Corosseo", "display_name":"Coliseum Ruins", "x":2424, "y":3131},
	{"internal_name":"DeathMountainHatago", "display_name":"Foothill Stable", "x":4306, "y":1928},
	{"internal_name":"DeathMountain_Entrance", "display_name":"Maw of Death Mountain", "x":4201, "y":1839},
	{"internal_name":"DodoraBridge", "display_name":"Luto's Crossing", "x":4537, "y":2501},
	{"internal_name":"DragonMarsh", "display_name":"Dragon Bone Mire", "x":912, "y":1642},
	{"internal_name":"EastDam", "display_name":"East Reservoir Lake", "x":4822, "y":2440},
	{"internal_name":"EastGerudoRuins", "display_name":"East Gerudo Ruins", "x":1654, "y":3944},
	{"internal_name":"EastPostTownRuin", "display_name":"East Post Ruins", "x":3015, "y":3282},
	{"internal_name":"Execution", "display_name":"Castle Town Prison", "x":2659, "y":2079},
	{"internal_name":"EzzuBridge", "display_name":"Eagus Bridge", "x":3485, "y":2970},
	{"internal_name":"FaronHatago000", "display_name":"Dueling Peaks Stable", "x":3880, "y":3463},
	{"internal_name":"FaronHatago001", "display_name":"Lakeside Stable", "x":3776, "y":4268},
	{"internal_name":"FaronHatago002", "display_name":"Highland Stable", "x":3264, "y":4225},
	{"internal_name":"FironeForestEntrance", "display_name":"Faron Woods", "x":3197, "y":4018},
	{"internal_name":"FlamingoSpa", "display_name":"Goflam's Secret Hot Spring", "x":1278, "y":712},
	{"internal_name":"FloriaBridge", "display_name":"Floria Bridge", "x":3868, "y":4233},
	{"internal_name":"FlowerSandbank", "display_name":"Floret Sandbar", "x":3432, "y":2939},
	{"internal_name":"ForestHatago", "display_name":"Woodland Stable", "x":3532, "y":1929},
	{"internal_name":"FrontGatePosttown", "display_name":"Gatepost Town Ruins", "x":2727, "y":3227},
	{"internal_name":"GameBalling", "display_name":"Pondo's Lodge", "x":1961, "y":1459},
	{"internal_name":"GameBitalockGolf", "display_name":"Tanagar Canyon Course", "x":1440, "y":2186},
	{"internal_name":"GameBitalockGolf", "display_name":"Tanagar Canyon Course", "x":1501, "y":1975},
	{"internal_name":"GameGutsCriff", "display_name":"Gut Check Rock", "x":4337, "y":744},
	{"internal_name":"GameMarathon", "display_name":"Footrace Check-In", "x":1678, "y":1915},
	{"internal_name":"GameShiledSurf", "display_name":"Selmie's Spot", "x":1518, "y":929},
	{"internal_name":"GameYabusame", "display_name":"Mounted Archery Camp", "x":2918, "y":4257},
	{"internal_name":"GameZarashiRace", "display_name":"Sand-Seal Rally", "x":1113, "y":4099},
	{"internal_name":"GarakishiVillage", "display_name":"Shadow Hamlet Ruins", "x":4526, "y":1350},
	{"internal_name":"GatakaraGarrison", "display_name":"Kolomo Garrison Ruins", "x":2767, "y":3136},
	{"internal_name":"Gerudo", "display_name":"Gerudo Town", "x":1082, "y":3957},
	{"internal_name":"GerudoCanyon_Entrance", "display_name":"Gerudo Canyon Pass", "x":2173, "y":3508},
	{"internal_name":"GerudoDesert_Entrance", "display_name":"Gerudo Desert Gateway", "x":1540, "y":3661},
	{"internal_name":"GerudoFossil", "display_name":"Gerudo Great Skeleton", "x":587, "y":4357},
	{"internal_name":"GerudoHatago", "display_name":"Gerudo Canyon Stable", "x":1598, "y":3612},
	{"internal_name":"Goron", "display_name":"Goron City", "x":3842, "y":1266},
	{"internal_name":"GoronBridge", "display_name":"Stolock Bridge", "x":3822, "y":1279},
	{"internal_name":"GutinizaPlainTomb", "display_name":"Guchini Plain Barrows", "x":3532, "y":4188},
	{"internal_name":"HachijoBridge", "display_name":"Owlan Bridge", "x":3163, "y":3136},
	{"internal_name":"Hateno", "display_name":"Hateno Village", "x":4796, "y":3560},
	{"internal_name":"HatenoGate", "display_name":"Fort Hateno", "x":4161, "y":3418},
	{"internal_name":"HatenoLabo", "display_name":"Hateno Ancient Tech Lab", "x":4889, "y":3562},
	{"internal_name":"HeburaFossil", "display_name":"Hebra Great Skeleton", "x":991, "y":657},
	{"internal_name":"HeburaLodge", "display_name":"Hebra Trailhead Lodge", "x":1213, "y":1362},
	{"internal_name":"HopesPlateau", "display_name":"Great Plateau", "x":2534, "y":3454},
	{"internal_name":"HyralBridge", "display_name":"Bridge of Hylia", "x":2979, "y":3754},
	{"internal_name":"HyruleCastle", "display_name":"Hyrule Castle", "x":2873, "y":2194},
	{"internal_name":"HyruleCastle_Hall_0", "display_name":"Sanctum", "x":2873, "y":1968},
	{"internal_name":"HyruleCastle_Hall_1", "display_name":"Second Gatehouse", "x":2914, "y":2074},
	{"internal_name":"HyruleCastle_Hall_2", "display_name":"First Gatehouse", "x":2818, "y":2093},
	{"internal_name":"HyruleCastle_Room_0", "display_name":"Observation Room", "x":2873, "y":2115},
	{"internal_name":"HyruleCastle_Room_1", "display_name":"Dining Hall", "x":2941, "y":2081},
	{"internal_name":"HyruleCastle_Room_10", "display_name":"East Passage", "x":2944, "y":2011},
	{"internal_name":"HyruleCastle_Room_11", "display_name":"West Passage", "x":2765, "y":2074},
	{"internal_name":"HyruleCastle_Room_2", "display_name":"Guards' Chamber", "x":2815, "y":2076},
	{"internal_name":"HyruleCastle_Room_3", "display_name":"Library", "x":2921, "y":1966},
	{"internal_name":"HyruleCastle_Room_5", "display_name":"Lockup", "x":2778, "y":1968},
	{"internal_name":"HyruleCastle_Room_6", "display_name":"Princess Zelda's Room", "x":2839, "y":2002},
	{"internal_name":"HyruleCastle_Room_7", "display_name":"Docks", "x":2872, "y":1905},
	{"internal_name":"HyruleCastle_Room_8", "display_name":"Princess Zelda's Study", "x":2808, "y":2008},
	{"internal_name":"HyruleCastle_Room_9", "display_name":"King's Study", "x":2914, "y":1939},
	{"internal_name":"HyruleCentralPlace", "display_name":"Central Square", "x":2873, "y":2307},
	{"internal_name":"HyruleDepthHatago", "display_name":"Outskirt Stable", "x":2275, "y":3134},
	{"internal_name":"HyruleGarrison", "display_name":"Hyrule Garrison Ruins", "x":2706, "y":2787},
	{"internal_name":"HyruleGround", "display_name":"Hyrule Kingdom", "x":2306, "y":3269},
	{"internal_name":"HyruleLabo", "display_name":"Royal Ancient Lab Ruins", "x":2367, "y":1985},
	{"internal_name":"HyrulePark", "display_name":"Hyrule Forest Park", "x":3096, "y":2034},
	{"internal_name":"HyrulePlace", "display_name":"Military Training Camp", "x":3412, "y":1762},
	{"internal_name":"HyruleTemple", "display_name":"Hyrule Cathedral", "x":3040, "y":2189},
	{"internal_name":"HyruleTower", "display_name":"Castle Town Watchtower", "x":3040, "y":2295},
	{"internal_name":"HyruleWater", "display_name":"Water Reservoir", "x":2701, "y":2241},
	{"internal_name":"HyruleWestHatago", "display_name":"Serenne Stable", "x":2220, "y":1600},
	{"internal_name":"IceHouse", "display_name":"Northern Icehouse", "x":1125, "y":3644},
	{"internal_name":"JogoBridge", "display_name":"Rebonae Bridge", "x":3411, "y":2516},
	{"internal_name":"JokuBridge", "display_name":"Proxim Bridge", "x":3103, "y":3301},
	{"internal_name":"Kakariko", "display_name":"Kakariko Village", "x":3903, "y":2992},
	{"internal_name":"KaturaCastle", "display_name":"Sage Temple Ruins", "x":2322, "y":2616},
	{"internal_name":"KingValley", "display_name":"Forgotten Temple", "x":2305, "y":1346},
	{"internal_name":"KingfisherSpa", "display_name":"Sherfin's Secret Hot Spring", "x":846, "y":753},
	{"internal_name":"KochuBridge", "display_name":"Kakariko Bridge", "x":3892, "y":3266},
	{"internal_name":"KumSpa", "display_name":"Sturnida Secret Hot Spring", "x":954, "y":1123},
	{"internal_name":"KunaiBridge", "display_name":"Aquame Bridge", "x":2435, "y":3008},
	{"internal_name":"LanayruEastEntrance", "display_name":"Lanayru Road - East Gate", "x":4594, "y":3077},
	{"internal_name":"LanayruWestEntrance", "display_name":"Lanayru Road - West Gate", "x":4152, "y":2853},
	{"internal_name":"LeMarbeBridge", "display_name":"Jeddo Bridge", "x":2155, "y":2565},
	{"internal_name":"LightningPlateau", "display_name":"Thundra Plateau", "x":1885, "y":2020},
	{"internal_name":"LittleBrotherBridge", "display_name":"Little Twin Bridge", "x":3857, "y":3574},
	{"internal_name":"LomeiIslands", "display_name":"Lomei Labyrinth Island", "x":5327, "y":675},
	{"internal_name":"LostForest", "display_name":"Lost Woods", "x":3370, "y":1543},
	{"internal_name":"MaronSpring", "display_name":"Malanya Spring", "x":3400, "y":4352},
	{"internal_name":"MarritaExchange", "display_name":"Maritta Exchange Ruins", "x":2097, "y":1687},
	{"internal_name":"MasazuBridge", "display_name":"Moat Bridge", "x":2692, "y":2170},
	{"internal_name":"MinakkareBridge", "display_name":"Sokkala Bridge", "x":4843, "y":1998},
	{"internal_name":"MinakkareBridgeEast", "display_name":"East Sokkala Bridge", "x":4930, "y":1952},
	{"internal_name":"MinakkareBridgeWest", "display_name":"West Sokkala Bridge", "x":4795, "y":1989},
	{"internal_name":"Mine", "display_name":"Abandoned North Mine", "x":3822, "y":1101},
	{"internal_name":"NantanCastle", "display_name":"South Lomei Labyrinth", "x":2102, "y":4267},
	{"internal_name":"NishojiBridge", "display_name":"Gleeok Bridge", "x":2347, "y":2905},
	{"internal_name":"NorthHatelHatago", "display_name":"Wetland Stable", "x":3444, "y":2586},
	{"internal_name":"Oasis", "display_name":"Kara Kara Bazaar", "x":1381, "y":3779},
	{"internal_name":"OrdinBridge", "display_name":"Bridge of Eldin", "x":4105, "y":1325},
	{"internal_name":"OrdinFossil", "display_name":"Eldin Great Skeleton", "x":3773, "y":651},
	{"internal_name":"OsanjoBridge", "display_name":"Helmhead Bridge", "x":3199, "y":1916},
	{"internal_name":"PostTownRuin", "display_name":"Outpost Ruins", "x":2876, "y":3337},
	{"internal_name":"PowerFountain", "display_name":"Spring of Power", "x":4877, "y":1163},
	{"internal_name":"RemainsElectric", "display_name":"Divine Beast Vah Naboris", "x":1619, "y":4375},
	{"internal_name":"RemainsElectric", "display_name":"Divine Beast Vah Naboris", "x":1944, "y":3813},
	{"internal_name":"RemainsFire", "display_name":"Divine Beast Vah Rudania", "x":4226, "y":1219},
	{"internal_name":"RemainsFire", "display_name":"Divine Beast Vah Rudania", "x":4268, "y":1192},
	{"internal_name":"RemainsWater", "display_name":"Divine Beast Vah Ruta", "x":4485, "y":2616},
	{"internal_name":"RemainsWater", "display_name":"Divine Beast Vah Ruta", "x":4831, "y":2412},
	{"internal_name":"RemainsWind", "display_name":"Divine Beast Vah Medoh", "x":1190, "y":1445},
	{"internal_name":"RemainsWind", "display_name":"Divine Beast Vah Medoh", "x":1192, "y":1568},
	{"internal_name":"RirikendoBridge", "display_name":"Oren Bridge", "x":4437, "y":2516},
	{"internal_name":"Rito", "display_name":"Rito Village", "x":1190, "y":1596},
	{"internal_name":"RitoHatago", "display_name":"Rito Stable", "x":1372, "y":1621},
	{"internal_name":"RiverSideHatago", "display_name":"Riverside Stable", "x":3169, "y":3047},
	{"internal_name":"RonronCity", "display_name":"Mabe Village Ruins", "x":2971, "y":2587},
	{"internal_name":"SaihokuCastle", "display_name":"North Lomei Labyrinth", "x":2587, "y":794},
	{"internal_name":"SarjonBridge", "display_name":"Sarjon Bridge", "x":3512, "y":4118},
	{"internal_name":"ShichijoBridge", "display_name":"Horwell Bridge", "x":3340, "y":2988},
	{"internal_name":"ShigonDam", "display_name":"Lanayru Promenade", "x":4354, "y":3081},
	{"internal_name":"ShijoBridge", "display_name":"Orsedd Bridge", "x":3265, "y":2252},
	{"internal_name":"ShinyarkiVillage", "display_name":"Rauru Settlement Ruins", "x":3352, "y":1871},
	{"internal_name":"SnowStatue", "display_name":"Statue of the Eighth Heroine", "x":822, "y":2749},
	{"internal_name":"SojijiPark", "display_name":"Sanidin Park Ruins", "x":2185, "y":2844},
	{"internal_name":"SotonkaBridge", "display_name":"Manhala Bridge", "x":2197, "y":3020},
	{"internal_name":"SouthGerudoLegacy", "display_name":"Arbiter's Grounds", "x":924, "y":4408},
	{"internal_name":"SouthMine", "display_name":"Southern Mine", "x":3828, "y":1513},
	{"internal_name":"StartPoint", "display_name":"Shrine of Resurrection", "x":2448, "y":3440},
	{"internal_name":"StonePillers", "display_name":"Ancient Columns", "x":1213, "y":2284},
	{"internal_name":"SusukadiBridge", "display_name":"Inogo Bridge", "x":4172, "y":2376},
	{"internal_name":"TabantaBridge", "display_name":"Tabantha Great Bridge", "x":1441, "y":2209},
	{"internal_name":"TabantaBridgeHatago", "display_name":"Tabantha Bridge Stable", "x":1534, "y":2226},
	{"internal_name":"TabantaCrater", "display_name":"Gisa Crater", "x":1034, "y":1955},
	{"internal_name":"TabantaHatago", "display_name":"Snowfield Stable", "x":2172, "y":1213},
	{"internal_name":"TabantaVillage", "display_name":"Tabantha Village Ruins", "x":1840, "y":1541},
	{"internal_name":"TamourHatago", "display_name":"East Akkala Stable", "x":5113, "y":1126},
	{"internal_name":"TamurulHatago_02", "display_name":"South Akkala Stable", "x":4574, "y":1653},
	{"internal_name":"TaserakaBridge", "display_name":"Thims Bridge", "x":3642, "y":2154},
	{"internal_name":"Taura", "display_name":"Lurelin Village", "x":4504, "y":4238},
	{"internal_name":"TimesShrine", "display_name":"Temple of Time", "x":2590, "y":3502},
	{"internal_name":"ToriaBridge", "display_name":"Boneyard Bridge", "x":3139, "y":2142},
	{"internal_name":"TotsugeBridge", "display_name":"Carok Bridge", "x":2456, "y":2262},
	{"internal_name":"Tower01", "display_name":"Hebra Tower", "x":1913, "y":1483},
	{"internal_name":"Tower02", "display_name":"Tabantha Tower", "x":1193, "y":2004},
	{"internal_name":"Tower03", "display_name":"Gerudo Tower", "x":1167, "y":3414},
	{"internal_name":"Tower04", "display_name":"Wasteland Tower", "x":1846, "y":3718},
	{"internal_name":"Tower05", "display_name":"Woodland Tower", "x":3441, "y":1697},
	{"internal_name":"Tower06", "display_name":"Central Tower", "x":2605, "y":2721},
	{"internal_name":"Tower07", "display_name":"Great Plateau Tower", "x":2719, "y":3347},
	{"internal_name":"Tower08", "display_name":"Dueling Peaks Tower", "x":3508, "y":3357},
	{"internal_name":"Tower09", "display_name":"Lake Tower", "x":2984, "y":3980},
	{"internal_name":"Tower10", "display_name":"Eldin Tower", "x":4087, "y":1721},
	{"internal_name":"Tower11", "display_name":"Akkala Tower", "x":4654, "y":1749},
	{"internal_name":"Tower12", "display_name":"Lanayru Tower", "x":4129, "y":2445},
	{"internal_name":"Tower13", "display_name":"Hateno Tower", "x":4367, "y":3566},
	{"internal_name":"Tower14", "display_name":"Faron Tower", "x":3665, "y":4136},
	{"internal_name":"Tower15", "display_name":"Ridgeland Tower", "x":2122, "y":2112},
	{"internal_name":"TurasuBridge", "display_name":"Horse God Bridge", "x":3295, "y":4369},
	{"internal_name":"UMiiVillage", "display_name":"Tarrey Town", "x":4982, "y":1692},
	{"internal_name":"ValleyVillage", "display_name":"Flight Range", "x":1074, "y":1355},
	{"internal_name":"WeaponCureSpring", "display_name":"Great Fairy Fountain", "x":1230, "y":2126},
	{"internal_name":"WeaponCureSpring", "display_name":"Great Fairy Fountain", "x":3988, "y":2922},
	{"internal_name":"WeaponCureSpring", "display_name":"Great Fairy Fountain", "x":5055, "y":1810},
	{"internal_name":"WeaponCureSpring", "display_name":"Great Fairy Fountain", "x":564, "y":4412},
	{"internal_name":"WetGarrison", "display_name":"Moor Garrison Ruins", "x":3760, "y":2415},
	{"internal_name":"WhiteZora", "display_name":"Zora's Domain", "x":4635, "y":2299},
	{"internal_name":"WiseFountain", "display_name":"Spring of Wisdom", "x":4972, "y":3171},
	{"internal_name":"XekuBridge", "display_name":"Digdogg Suspension Bridge", "x":2167, "y":3271},
	{"internal_name":"YashinoLegacy", "display_name":"Palmorae Ruins", "x":4723, "y":4169},
	{"internal_name":"ZonauLegacy", "display_name":"Zonai Ruins", "x":3421, "y":3982}
];
